### ISSUE TITLE
Build/Provide helm:3.0.0-beta.1

### ISSUE THREAD

**Issue by pniederlag** [alpine-docker/helm#10]
Would be nice if you could ship a container for the recently released v3.0.0-beta.1

https://github.com/helm/helm/releases/tag/v3.0.0-beta.1

Many thx for your efforts,
greets,
Peter

**Comment by pniederlag** [comment]
Ooops, there's already a beta.2 :->
https://github.com/helm/helm/releases/tag/v3.0.0-beta.2

**Comment by MisterCoder** [comment]
I have just submitted a PR for this here https://github.com/alpine-docker/helm/pull/11

**Comment by MisterCoder** [comment]
@pniederlag there we go, 3.0.0-beta.2 is now tagged.

https://hub.docker.com/r/alpine/helm/tags
