### ISSUE TITLE
Build for "v3.0.0-beta.3" not running?

### ISSUE THREAD

**Issue by MisterCoder** [alpine-docker/helm#12]
Not had time to look in to this yet but v3.0.0-beta.3 is not being built. It's been out for 20+ days.

https://github.com/helm/helm/releases/tag/v3.0.0-beta.3

**Comment by ozbillwang** [comment]
Thanks to point this, I have fixed. 

https://travis-ci.org/alpine-docker/helm/builds/592489635

**Comment by markmssd** [comment]
It hasn't ran for `v3.0.0-beta.4` (well, it released only 8 hours ago). I think there's ways to trigger the build automatically (I've never done it myself), but I'd be happy to research and open a PR for it if you want. Cheers!

**Comment by ozbillwang** [comment]
travis (free account) can only trigger build per day, week or month. The previous build was run about 16 hours ago. 

So wait for another 8 hours, it should be ready.
