### ISSUE TITLE
image alpine:edge error when apk add

### ISSUE THREAD

**Issue by SteveOzo** [alpine-docker/helm#13]
Actually image alpine:edge can run apk update or apk add.

`/ # apk update

fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
WARNING: Ignoring APKINDEX.066df28d.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
WARNING: Ignoring APKINDEX.b53994b4.tar.gz: No such file or directory
2 errors; 14 distinct packages available

/ # apk add --no-cache curl

fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]`

**Comment by ozbillwang** [comment]
Thanks to point this out. Seems `update` is broken in `alpine:edge` image currently.

**Comment by ozbillwang** [comment]
Fixed. `2.16.0` has been built and pushed by travis ci

https://travis-ci.org/alpine-docker/helm/builds/609017996
