### ISSUE TITLE
alpine:edge or alpine:3 selector support

### ISSUE THREAD

**Issue by tuananhnguyen-ct** [alpine-docker/helm#14]
Docker alpine was switched from edge to 3 following https://github.com/alpine-docker/helm/issues/13, but we want to keep using alpine:edge to be able to install/use python 3.8 (instead of 3.7) for some reasons (3.7 has some bugs that broke our pipeline).

Is it possible to have the alpine version as selectable tag?

**Comment by ozbillwang** [comment]
you can copy the `Dockerfile` directly, switch to `alpine:edge`, add your code, such as install python 3.8, then push to public docker registry server or your own private registry server if you have.
