### ISSUE TITLE
Latest pins to 2.16.3 instead of 3.1.0

### ISSUE THREAD

**Issue by IamRFC1918** [alpine-docker/helm#15]
Hi,

today with the latest build, the latest image tag pins to the digest (9d9fab00e068) of version 2.16.3.
The days before, latest tags to the version 3 image.

I think thats an error and should be corrected.

Regards,
Frank

**Comment by ozbillwang** [comment]
I click the link 

https://github.com/helm/helm/releases/latest

Currently it is version 2.16.3

So this issue need be fixed by upstream. 

Could you raise the issue to https://github.com/helm/helm

**Comment by ozbillwang** [comment]
anyway, I have raised an issue to helm

https://github.com/helm/helm/issues/7598

**Comment by IamRFC1918** [comment]
Thank you @ozbillwang :)

**Comment by ozbillwang** [comment]
@IamRFC1918 

It has been fixed by #16 . Please check.
