### ISSUE TITLE
Image does not follow official entrypoint advice

### ISSUE THREAD

**Issue by gr-harryc** [alpine-docker/helm#19]
https://github.com/docker-library/official-images#consistency

> All official images should provide a consistent interface. A beginning user should be able to docker run official-image bash (or sh) without needing to learn about --entrypoint

As the entrypoint is set to `helm` this does not work. On jenkins the default docker container command is `cat` to halt the image to allow other processes to be run inside it. Since the entrypoint is set to helm the command is essentially `helm cat` which is not valid. 

Please consider unsetting the entrypoint or creating an entrypoint script to run commands that can be found on $PATH else run helm with the arguments specified.

**Comment by joshiraez** [comment]
I'm on it actually. We had this problem

**Comment by felipecrs** [comment]
@ozbillwang ping

I believe the only reason not to simply accept the PRs which fix this is not to break the backward compatibility. Right?

**Comment by ozbillwang** [comment]
Please discuss in the PR #20

It has some version hardcoded issue.

**Comment by algra4** [comment]
I have the same problem 😔 @
@joshiraez  @ozbillwang Do you have a workaround until the problem is solved?
