### ISSUE TITLE
version 2.16.5 is missing

### ISSUE THREAD

**Issue by ahmadalli** [alpine-docker/helm#22]

**Comment by ozbillwang** [comment]
good point. 

The script moves on and check v3.x version only, but seems helm team is still working on 2.x versions. 

Let me see if I can add this check back.

**Comment by ozbillwang** [comment]
Fixed with commit https://github.com/alpine-docker/helm/commit/743558536510aaecfa222314977a960176dc7eed

**Comment by ozbillwang** [comment]
I made a feature branch called `feature/mend` which will be only triggered if some versions are missed. 

this branch's code will go through all releases/tags to make sure all of them are buld and pushed. 

the code on master branch will only check the last 30 releases.
