### ISSUE TITLE
Documentation out of date on Docker Hub

### ISSUE THREAD

**Issue by jsolbrig** [alpine-docker/helm#24]
It looks to me like the documentation on Docker Hub is out of date with regards to volumes. It doesn't match what is in the current readme. Would it be possible to update this? I spent nearly an hour sorting out that I needed to mount `/root/.cache/helm`, not just `/root/.helm`

**Comment by ozbillwang** [comment]
sure, I added comments there, since it is a manual job, I didn't update it frequently.

```
## README and its updates

the readme here is not keep updated, it is better to get updates from its source repository:

https://github.com/alpine-docker/helm/blob/master/README.md
```
