### ISSUE TITLE
Missing some versions

### ISSUE THREAD

**Issue by felipecrs** [alpine-docker/helm#26]
The versions 2.16.10, 2.16.11, and 2.16.12 are missing.

**Comment by ozbillwang** [comment]
Do we really need helm 2 any more?

**Comment by felipecrs** [comment]
I used this docker image to test a bug against different versions of Helm in https://github.com/helm/helm/issues/8865. Then I figured out that the issue was introduced in Helm v2.16.0, but I was not able to test using its latest versions since it's not available.

> Do we really need helm 2 any more?

Yes, it was not deprecated.

**Comment by henres** [comment]
Hello,
If possible yes please !

**Comment by svenmueller** [comment]
Version 2.17.0 is missing too (important version since the focus is on Helm v2 end of life support.)

https://github.com/helm/helm/releases/tag/v2.17.0

**Comment by ozbillwang** [comment]
I currently have no plan to support helm 2, if you do need, please raise the PR.

**Comment by felipecrs** [comment]
@ozbillwang I sent a PR.

**Comment by felipecrs** [comment]
@svenmueller the 2.17.0 is now available in Docker Hub.

**Comment by felipecrs** [comment]
@svenmueller the 2.17.0 is now available in Docker Hub.
