### ISSUE TITLE
latest tag must be latest release instead of latest rc release

### ISSUE THREAD

**Issue by ahmadalli** [alpine-docker/helm#3]
currently latest release of helm is `1.13.1` accessible by https://github.com/helm/helm/releases/latest while the next two releases are prereleases and must not be tagged by latest on docker hub. or there should be `stable` tag too

**Comment by ozbillwang** [comment]
Latest should be always latest.

The idea to add a new tag `stable` is reasonable.

**Comment by ozbillwang** [comment]
Do we really need care of rc or alpha releases? 

currently I check the release with this url https://api.github.com/repos/${repo}/tags, it will pick up the latest, whatever it is alpha, rc or formal release. 

if we don't care of rc and alpha releases, I will change the url to yours.

**Comment by ahmadalli** [comment]
I don't see any case where rc is useful unless for testing purposes.

**Comment by ozbillwang** [comment]
@ahmadalli 

After thinking your request, I finally go with exist way. I updated the README to recommend to use the tag with version always. TAG `latest` is evil, shouldn't be used for any serious jobs, such as production deployment. 

Second, helm does need version to be updated on both side always, kubernetes server and clients. Otherwise, it can't work properly. So nominate a version will be the best practice.

**Comment by ahmadalli** [comment]
@ozbillwang `latest` might be evil but `stable` isn't. We can have that for stable releases. I tend to keep my tiller update and `stable` would save me from changing tag on my cd pipelines periodically.

About your second point, I faced the issue when I was using the latest tag and my CD pipeline would fail because my server's tiller didn't support rc version of helm which was the `latest`

What I'm asking is having `stable` tag besides on `latest` tag

**Comment by ozbillwang** [comment]
That's why I recommend to update your CICD to use the right helm version, more than to use `latest`, will this be the problem in your environment?

**Comment by ozbillwang** [comment]
For tag `stable`, I will work on it.
