### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by odidev** [alpine-docker/helm#31]
Hi Team,

I am trying to use “helm” over ARM64v8 but it seems it does not have an arm64 supported tag in docker hub. After the below changes, the image was successfully uploaded to Dockerhub.

-  **Dockerfile:** Added a new build argument ARCH which will install the binaries as per the architecture.

-  **.travis.yml:** Added architecture arm64-graviton2 and installed jq in .travis.yml file to build, test, and release image for arm64.

-  **Build.sh:** Added check so that the image for arm64 will be pushed with name <image name>:<tag>-arm64 and also provided the architecture as build argument for building the image for a particular architecture.

**Commit Link:** https://github.com/Fayeal/helm/commit/86a79a6b989ceecdc357c7275996412d48c2481f

**Travis Link**: https://travis-ci.com/github/Fayeal/helm/builds/213286679

**Dockerhub Link:** https://hub.docker.com/repository/docker/odidev/helm

It looks that you are using travis-ci.org and as per https://blog.travis-ci.com/2020-09-11-arm-on-aws the arm64-graviton support is added for travis-ci.com and travis is also shutting down travis-ci.org.

It will be very helpful if this image is released for the arm64 platform. If interested, I can raise a PR. But first, we need to migrate this project from travis-ci.org to travis-ci.com.

Please let me know if any help is required.

**Comment by ozbillwang** [comment]
Thanks, I don't have plan to support others currently.

**Comment by ozbillwang** [comment]
I took a look on your code. Looks neat. 

Do you have the latest Macbook which is ARM64 already and run a manual test to confirm this new Arch image works?

**Comment by odidev** [comment]
I have a local arm64 Linux machine, tested it and it is working. I am happy to contribute whenever any suggestions are required.

**Comment by ozbillwang** [comment]
I got this document, seems this is a right direction to deal with multi-arch

https://docs.docker.com/docker-for-mac/multi-arch/

**Comment by ozbillwang** [comment]
I manually built a multi-arch image , tag is **3.5.0-rc.1**

![image](https://user-images.githubusercontent.com/8954908/104883378-cb06b100-59b8-11eb-9112-02330ce1dacd.png)

Could you run the command on your arm64 linux machine

```
docker run -ti --rm alpine/helm:3.5.0-rc.1 version
```

What's the output?

**Comment by ozbillwang** [comment]
Looks fine from my view, I test it on my mac (x86_64)

```
$ docker run  -ti --rm --platform linux/arm64 --entrypoint=sh -t alpine/helm:3.5.0-rc.1
/apps # uname -m
aarch64
/apps #
```

```
$ docker run  -ti --rm --platform linux/arm64 -t alpine/helm:3.5.0-rc.1 version
version.BuildInfo{Version:"v3.5.0-rc.1", GitCommit:"f546ebb1aca7c45a09a71886b720b6e11d45e9d8", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

But still need a final confirmation

**Comment by ozbillwang** [comment]
The Dockerfile for git has no same issue. I will build a special version for your test.

**Comment by ozbillwang** [comment]
Find a bug, that the arch is hard coded in `Dockerfile`

https://github.com/alpine-docker/helm/blob/master/Dockerfile#L10

need a fix

**Comment by odidev** [comment]
@ozbillwang 

As per your suggestion, I ran the `“docker run -ti --rm alpine/helm:3.5.0-rc.1 version“` command, and I was getting the below result.
```
$ docker run -ti --rm alpine/helm:3.5.0-rc.1 version
standard_init_linux.go:211: exec user process caused "exec format error"  

```
I have checked the source code on github and can see that the helm binary is hardcoded for amd64. Please find the reference [here](https://github.com/alpine-docker/helm/blob/master/Dockerfile#L10)  That is why docker run command is giving the “exec format error”.

It’s working, after giving  ‘--entrypoint=sh’ flag along with the “docker run” command. I suppose it is because  ‘--entrypoint=sh’ will override the default entrypoint in the dockerfile, i.e. ”helm”, which is hardcoded for AMD64. 

I have successfully run it in my forked repo after doing some changes in dockerfile. You can check my changes at https://github.com/odidev/helm/blob/helm_arm/Dockerfile

If agreed, I can raise a PR.

**Comment by ozbillwang** [comment]
your `Dockerfile` looks fine (https://github.com/odidev/helm/blob/helm_arm/Dockerfile)

But we need redesign to support multi-arch with simple way via `docker buildx build` command

**Comment by odidev** [comment]
I have used the above-mentioned method to test as well in arm64. As you mentioned, we can redesign it with buildx without testing in arm64.

If interested, I can do the changes and will raise a PR.

**Comment by ozbillwang** [comment]
sure

**Comment by basert** [comment]
Any news on this? I could use this to run some deployments on my raspberry-pi k3s cluster.

**Comment by ozbillwang** [comment]
no. i stuck to build multi-arch images within Travis agent, if can't, i would look for solution on others, such as github action or circleci

**Comment by ozbillwang** [comment]
all related multi-arch related issues, please follow up at https://github.com/alpine-docker/multi-arch-docker-build-on-ci/issues/1

**Comment by ozbillwang** [comment]
the change is ready and merged to master branch.

1. version 3.5.4 and 3.6.0-rc.1 are manually pushed by me 
2. older version will be not updated as multi-arch images
3. newer vesions from now on will be multi-arch images (`--platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6,linux/ppc64le,linux/s390x`)
4. tag `latest` doesn't suppoort multi-arch yet, because I can't find a good way to tag it only without rebuild it.

reference build templates: 

https://github.com/alpine-docker/multi-arch-docker-build-on-ci

**Comment by ozbillwang** [comment]
@basert 

could you confirm if it is fine on your raspberry-pi k3s?

**Comment by basert** [comment]
Doesn't seem to work for me, getting `format error`, which usually means platform:
```
root@raspberrypi:/opt# docker run -ti --rm -v $(pwd):/apps -w /apps alpine/helm:3.5.4
Unable to find image 'alpine/helm:3.5.4' locally
3.5.4: Pulling from alpine/helm
e160e00eb35d: Already exists 
670e6e1656eb: Pull complete 
d4e9ed060a96: Pull complete 
Digest: sha256:9a4b23d3c107c0a086616c9a729beb105c5c5e6ae0264d605d05141eddf8f435
Status: Downloaded newer image for alpine/helm:3.5.4
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by basert** [comment]
This works on rpi now, after changes done in https://github.com/alpine-docker/helm/pull/38
