### ISSUE TITLE
dockerhub page incorrectly reflects volume mounts for config persistence

### ISSUE THREAD

**Issue by DazWilkin** [alpine-docker/helm#34]
The dockerhub "Usage" documentation is incorrect:

https://hub.docker.com/r/alpine/helm

```bash
docker run -ti --rm -v $(pwd):/apps \
    -v ~/.kube:/root/.kube \
    -v ~/.helm:/root/.helm \
    alpine/helm
```

The GitHub README correctly describes [Usage](https://github.com/alpine-docker/helm/blob/master/README.md#usage):

```bash
docker run -ti --rm -v $(pwd):/apps -w /apps \
    -v ~/.kube:/root/.kube \
    -v ~/.helm:/root/.helm \
    -v ~/.config/helm:/root/.config/helm \
    -v ~/.cache/helm:/root/.cache/helm \
    alpine/helm
```

The `.config` and `.cache` directories are missing from dockerhub losing e.g. repo persistence across invocations:

Assuming the following are prefixed:
```bash
docker run \
--interactive --tty --rm \
--volume=${HOME}/.kube:/root/.kube \
--volume=${PWD}/:/apps \
--volume=${PWD}/.helm:/root/.helm \
alpine/helm:3.5.2 ...
```
Then:
```bash
repo list
Error: no repositories to show

repo add xxxx ...
"xxxx" has been added to your repositories

repo list
Error: no repositories to show
```

Nit: for documentation, I think it's more helpful to use `--long-flags` to aid clarity and be more inclusive of those less familiar

**Comment by ozbillwang** [comment]
are you fine to raise PR to fix it?

**Comment by DazWilkin** [comment]
The Dockerhub page now reflects correctly the instructions of the `README`.
