### ISSUE TITLE
Add kubectl (or kustomize)

### ISSUE THREAD

**Issue by judge-red** [alpine-docker/helm#35]
Please consider adding `kubectl` or `kustomize` to the image. `kustomize` is the most common tool used in Helm post rendering, and mentioned several times in the docs:
https://helm.sh/docs/topics/advanced/

`kustomize` has since been integrated into `kubectl` (as `kubectl kustomize`, `kubectl apply -k`, etc.), so I think it would be preferable to include the latter as it could be a handy tool to have in other situations as well.

**Comment by ozbillwang** [comment]
good to know. 

the problem i need resolve here is, what kubectl and kustomize version I should install. latest? but later if someone asks for new kubectl versions, what can I do?

**Comment by ozbillwang** [comment]
I maintain another image, called "alpine/k8s" . Maybe i can install helm in it. that one has more tools installed
