### ISSUE TITLE
3.6.0 tag not published to Docker Hub

### ISSUE THREAD

**Issue by sichapman** [alpine-docker/helm#39]
Title says it all - Helm 3.6 has been out for a couple of weeks now

**Comment by ozbillwang** [comment]
Thanks for the report. 

Seems it related to the latest update (#37)

from the log, it detected the latest version 3.60 is not published, but after build the image, it doesn't push the image properly. 

2 problems here:

1. after build, image with tag 3.6.0 is not pushed. No error I can check
2. when update latest tag, the command is failed, but build is not marked as failed.

**Comment by jnoordsij** [comment]
I just had some problems using the `latest` tag in one of my pipelines; it seems like currently only `linux/ppc64le` architecture is pushed to 3.6.1 (and thus latest). 

By the looks of your Travis CI logs, something is still off (see https://travis-ci.com/github/alpine-docker/helm/jobs/520131672#L521).

**Comment by ozbillwang** [comment]
@jnoordsij 

the problem will be fixed by a manual deployment, please wait for half hour.

@sichapman 

for the build issue, I have doubled check the codes, seems the original codes have no issue run on local (I tried on mac, ubuntu).

so it is a limitation in Travis CI. from the error message is about `busybox` trigger, from its name, my understanding is, travis ci has a protection to block a build if use too much CPU.

Not sure this is related to new travis ci or not, since we ask to migrate from travis-ci.org to travis-ci.com

Will approach to Travis CI for help.

Currently I have to manually build these images.

**Comment by ozbillwang** [comment]
looks I hit this issue, not travis ci 's problem

https://gitlab.alpinelinux.org/alpine/aports/-/issues/12406

**Comment by ozbillwang** [comment]
Downgrad to base image `alpine:3.12` doesn't fix this issue, here are more details for this issue

https://github.com/alpinelinux/docker-alpine/issues/135

https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

```
musl 1.2
musl has been upgraded to 1.2. This release changes the definition of time_t on 32-bit systems. See the musl time64 release notes for more details.

time64 requirements
The following important information applies for users of x86, armv7, and armhf (currently supported 32-bit architectures), including 32-bit Docker containers on 64-bit hosts.

All self-compiled packages must be manually rebuilt after upgrading, even if relocation/SONAME errors are not encountered.

musl 1.2 uses new time64-compatible system calls. Due to runc issue 2151, these system calls incorrectly returned EPERM instead of ENOSYS when invoked under a Docker or libseccomp version predating their release. Therefore, Alpine Linux 3.13.0 requires one of the following:

runc v1.0.0-rc93
if using Docker's Debian repositories, this is part of containerd.io 1.4.3-2
if using Docker Desktop for Windows or Mac, this is part of Docker Desktop 3.3.0
Docker 19.03.9 (which contains backported moby commit 89fabf0) or greater, AND libseccomp 2.4.2 (which contains backported libseccomp commit bf747eb) or greater. In this case, to check if your host libseccomp is time64-compatible, invoke scmp_sys_resolver -a x86 clock_gettime64 for x86 containers, or scmp_sys_resolver -a arm clock_gettime64 for armhf or armv7 containers. If 403 is returned, time64 is supported. If -1 is returned, time64 is not supported. Note that if runc is older than v1.0.0-rc93, Docker must still be at least version 19.03.9, regardless of the result of this command.
In order to run under old Docker or libseccomp versions, the moby default seccomp profile should be downloaded and on line 2, defaultAction changed to SCMP_ACT_TRACE, then --seccomp-profile=default.json can be passed to dockerd, or --security-opt=seccomp=default.json passed to docker create or docker run. This will cause the system calls to return ENOSYS instead of EPERM, allowing the container to fall back to 32-bit time system calls. In this case, the container will not be compatible with dates past 2038.

Alternatively, --security-opt=seccomp=unconfined can be passed with no default.json required, but note that this will reduce the security of the host against malicious code in the container.

```

**Comment by ozbillwang** [comment]
@sichapman  

can you test on tag 3.6.2 which is built by Travis now.

I did a change to avoide to install **curl and ca-certificates** , but need make sure there is no break to any helm chart commands.

```diff
         s390x) ARCH=s390x; ;; \
         *) echo "un-supported arch, exit ..."; exit 1; ;; \
     esac && \
-    apk add --update --no-cache curl ca-certificates wget && \
-    curl -L ${BASE_URL}/helm-v${VERSION}-linux-${ARCH}.tar.gz |tar xvz && \
+    apk add --update --no-cache wget && \
+    wget ${BASE_URL}/helm-v${VERSION}-linux-${ARCH}.tar.gz -O - | tar -xz && \
     mv linux-${ARCH}/helm /usr/bin/helm && \
     chmod +x /usr/bin/helm && \
-    rm -rf linux-${ARCH} && \
-    apk del curl && \
-    rm -f /var/cache/apk/*
+    rm -rf linux-${ARCH}
+
+RUN chmod +x /usr/bin/helm
```

**Comment by sichapman** [comment]
3.6.2 pulled and working well for us here for our usage (lint, template, upgrade/install/uninstall).

**Comment by ozbillwang** [comment]
let's wait for a new helm release (would be auto provisioned by Travis CI) and confirm.

**Comment by ozbillwang** [comment]
release 3.6.3 is released 5 days before, but travis ci (the free cicd tool I am using currently) changed their free plan, I have used the credit and need wait for reset on 19th July. 

I have reduced the schedule build from daily to weekly to reduce credit usage.

So let wait for tomorrow build

**Comment by ozbillwang** [comment]
version 3.6.3 is released, but since we totally get 25k free credit, I am not sure when it will be used out. 

Currently Travis CI doesn't refresh credit monthly.

Let's see.
