### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by allinonedashboard** [alpine-docker/helm#41]
Hi Team,

I am trying with the docker helm image and getting the below error.
Can you help me on below.
![image](https://user-images.githubusercontent.com/50626781/123069716-f465b600-d40a-11eb-9bad-5e5ee60858ae.png)
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused

Expected output: able to see the list of releases.
Let me know for any more inputs.

**Comment by ozbillwang** [comment]
your ~/.kube/config is set to localhost, but when you run helm in docker, the localhost is helm's container.

You can update to your laptop's IP.

**Comment by allinonedashboard** [comment]
Hi @ozbillwang 

You mean on the server details i need to update my laptop public ip address?

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: *********************
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: ****************
    server: https://127.0.0.1:51987
  name: kind-kind
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: *****************
    client-key-data: *****************
- name: kind-kind
  user:
    client-certificate-data: *****************
    client-key-data: L***********************

**Comment by ozbillwang** [comment]
what I knew is, you have two k8s clusters, one is docker desktop for mac/windows, the other is kubernetes in docker (kind)

You should be fine to access docker desktop for mac/windows.

For kind, if we replace `127.0.0.1` to local IP or `kubernetes.docker.internal`, it is not allowed

```
Unable to connect to the server: x509: certificate is valid for kind-control-plane, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, not kubernetes.docker.internal
```

**Comment by ozbillwang** [comment]
anyway, I have raised a feature request to KIND

https://github.com/kubernetes-sigs/kind/issues/2325

**Comment by ozbillwang** [comment]
ok, it can be fixed by this way (`--network host`), with that, you don't have to change the ip of `127.0.0.1` any more.

```
docker run -ti --rm -v ~/.kube:/root/.kube --network host alpine/helm list
```

**Comment by allinonedashboard** [comment]
Hi @ozbillwang 

Thanks for the help. I tried the same. But still its the same issue.
![image](https://user-images.githubusercontent.com/50626781/123293537-fb282200-d50b-11eb-9099-e22f7da18401.png)

**Comment by ozbillwang** [comment]
remove -p 8080:8080 in your command
