### ISSUE TITLE
Unable to use image on linux/amd64 systems since 3.6.x

### ISSUE THREAD

**Issue by sboschman** [alpine-docker/helm#42]
Since 3.6.x it seems the images are ppc64le only?

```
$ docker run alpine/helm:3.6.1
WARNING: The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

```
$ docker run alpine/helm:3.6.0
WARNING: The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

Tag 3.5.4 works fine:
```
$ docker run alpine/helm:3.5.4    
The Kubernetes package manager

Common actions for Helm:

- helm search:    search for charts
- helm pull:      download a chart to your local directory to view
- helm install:   upload the chart to Kubernetes
- helm list:      list releases of charts
```

Is this intented or did it break with https://github.com/alpine-docker/helm/pull/38 ?

**Comment by daanemanz** [comment]
We're running into the same issue:

```
~#@❯ docker run --rm alpine/helm:latest version
WARNING: The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

The weird thing is that the image is successful when running from the command line, but when running in a CI pipeline the job fails.

**Comment by mcallaghan-geotab** [comment]
It looks like someone accidentally rebuilt all the OLD tags and overwrote them only for `linux/ppc64le` :x: :exclamation: 
https://hub.docker.com/r/alpine/helm/tags?page=1&ordering=last_updated

**Comment by shayonj** [comment]
There is some more context on the overview section (sharing for posterity)
![image](https://user-images.githubusercontent.com/1100970/123861654-6e0f0f80-d8f5-11eb-9874-5124cd3e7af0.png)
https://hub.docker.com/r/alpine/helm

**Comment by ozbillwang** [comment]
I knew the issue, but hub.docker.com doesn't allow me to delete a tag. 

I am looking for help from docker, please wait.

As recommend, don't use  tag "latest" for your production deployment

**Comment by ozbillwang** [comment]
manually build 3.6.0. 3.6.1 and 3.6.2, and latest as well. 

should be fine now.

I still highly recommend, don't use tag "**latest**" for your production deployment

**Comment by ozbillwang** [comment]
@sboschman @daanemanz @mcallaghan-geotab @shayonj 


can you test on tag 3.6.2 which is built by Travis now.

the package `ca-certificates` doesn't work properly when build arm image on amd64 ubuntu (travis agents)

So I did a change to avoid to install **curl and ca-certificates** , but need make sure there is no break to any helm chart commands.

```diff
         s390x) ARCH=s390x; ;; \
         *) echo "un-supported arch, exit ..."; exit 1; ;; \
     esac && \
-    apk add --update --no-cache curl ca-certificates wget && \
-    curl -L ${BASE_URL}/helm-v${VERSION}-linux-${ARCH}.tar.gz |tar xvz && \
+    apk add --update --no-cache wget && \
+    wget ${BASE_URL}/helm-v${VERSION}-linux-${ARCH}.tar.gz -O - | tar -xz && \
     mv linux-${ARCH}/helm /usr/bin/helm && \
     chmod +x /usr/bin/helm && \
-    rm -rf linux-${ARCH} && \
-    apk del curl && \
-    rm -f /var/cache/apk/*
+    rm -rf linux-${ARCH}
+
+RUN chmod +x /usr/bin/helm
```

**Comment by sboschman** [comment]
tag 3.6.2 seems to work allright in our CI pipeline :+1:

**Comment by ozbillwang** [comment]
great, I wait for more feedback, if all fine, I will remove tag 3.6.0 and 3.6.1 and built them from travis as well.
